app/main/views.py
import os
from datetime import datetime

from flask import Response
from flask import render_template, request, redirect, url_for
from flask import Blueprint, jsonify
from ..models import Article, Comment, Reply, User, Permission
from .forms import ArticleForm, CommentForm
from flask_login import login_required, current_user
from .. import db
from ..utils.decorators import permission_required
from flask import current_app

main = Blueprint('main', __name__)


@main.route("/")
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config.get("ARTICLE_PER_PAGE", 10)
    pagination = Article.query.filter_by(auther_id=current_user.id).\
        order_by(Article.created.desc()).paginate(page, per_page=per_page)
    articles = pagination.items
    return render_template("index.html", pagination=pagination, articles=articles)


@main.route("/upload", methods=["POST"])
def upload():
    file = request.files.get('editormd-image-file')
    if not file:
        res = {
            'success': 0,
            'message': '上传失败'
        }
    else:
        ex = os.path.splitext(file.filename)[1]
        filename = os.path.join(current_app.root_path, 'static', 'img', datetime.now().strftime('%Y%m%d%H%M%S') + ex)
        print(filename)
        file.save(filename)
        res = {
            'success': 1,
            'message': '上传成功',
            'url': url_for('.image', name=filename)
        }
    return jsonify(res)


@main.route('/image/<name>')
def image(name):
    with open(name, 'rb') as f:
        resp = Response(f.read(), mimetype="image/jpeg")
    return resp


@main.route('/article/list', methods=['GET'])
@login_required
def article_list():
    return render_template("article/article_list.html")


@main.route('/article/data', methods=['GET'])
@login_required
def article_data():
    res = []
    articles = Article.query.options(db.joinedload("user")).filter_by(auther_id=current_user.id).all()
    for article in articles:
        res.append(
            {
                "id": article.id,
                "title": "<a href='%s' style='cursor:pointer'>%s</a>"
                         % (article.id, article.title),
                "auther": article.user.name,
                'edit': "<a href='edit/%s' style='cursor:pointer' >编辑<a>" % article.id
            }
        )

    return jsonify(res)


@main.route('/article/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.COMMENT)
def comments(id):
    article = Article.query.get_or_404(id)
    form = CommentForm(request.form)

    # 保存评论
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, article_id=id, auther_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for(".comments", id=id))
    article.hit_numers += 1
    return render_template("article/details.html",
                           title=article.title,
                           form=form,
                           article=article)


@main.route('/article/edit', methods=['GET', 'POST'])
@main.route('/article/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id=0):
    """
    :param id: 文章id
    :return: post提交，当id为0时，编辑发布新文章，否则编辑旧博客，发布后更新数据库，
    跳转到.comments将博客和评论一并呈现
             get请求时，将文章输入到编辑框中
    """
    form = ArticleForm(request.form)
    # post提交
    if form.validate_on_submit():
        if id == 0:
            article = Article(user=current_user)
        else:
            article = Article.query.get_or_404(id)
        article.body = form.body.data
        article.title = form.title.data

        db.session.add(article)
        db.session.commit()
        # url_for调用处理函数函数名
        return redirect(url_for('.comments', id=article.id))
    # get 编辑时
    title = u'添加文章'
    if id > 0:
        article = Article.query.get_or_404(id)
        form.body.data = article.body
        form.title.data = article.title
        title = u'编辑 %s' % article.title

    return render_template('article/edit.html',
                           title=title,
                           form=form)


@main.route('/article/delete/<int:id>', methods=['DELETE'])
@permission_required(Permission.WRITE)
def delete_article(id):
    article = Article.query.get(id)
    db.session.delete(article)
    db.session.commit()
    res = {
        'success': 0,
        'message': '删除成功',
    }
    return jsonify(res)


@main.route('/reply/<int:article_id>/<int:comment_id>', methods=['POST'])
@login_required
@permission_required(Permission.COMMENT)
def reply(article_id, comment_id):
    reply = Reply(comment_id=comment_id, auther_id=current_user.id)
    reply.body = request.form.get("values")
    db.session.add(reply)
    db.session.commit()
    ret = {
        "data": reply.body
    }
    return jsonify(ret)


@main.route('/about')
def about():
    return render_template('about.html', title=u'关于')

app/templates/article/_articles.html
{% if articles %}
    {%  for article in articles %}
        <h3 class="text-primary"><a href="{{url_for('main.comments', id=article.id)}}">{{ article.title }}</a></h3>
        <p>
            {{ article.body_html| striptags |truncate }}
            <small><a href="{{ url_for('main.comments', id=article.id) }}">阅读更多</a></small>
        </p>
        <small>
            评论<a href="{{ url_for('main.comments', id=article.id) }}">({{ article.comments | length }})</a>
            点击<a href="{{ url_for('main.comments', id=article.id) }}">({{ article.hit_numers }})</a>
            日期 <span>{{ article.created | strftime }}</span>
        </small>
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>文章空空如也</h5>
    </div>
{% endif %}

app/templates/article/article_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
 {% block scripts %}
{% endblock %}
{%  include ['includes/_article_list.html'] %}

{% block content %}
    <div class="container">
    <div>
        <button id="btn_delete" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>删除
        </button>
    </div>
    <table id="tableId"></table>
    </div>
<script type="text/javascript">
    $('#tableId').bootstrapTable({
            url: '/article/data',               //请求后台的URL（*）
            method: 'get',                      //请求方式（*）
            striped: true,                      //是否显示行间隔色
            toolbar : '#toolbar',
            cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
            pagination: true,                   //是否显示分页（*）
            sortable: false,                     //是否启用排序
            sortOrder: "asc",                   //排序方式
            sidePagination: "client",           //分页方式：client客户端分页，server服务端分页（*）
            search: true,
            showColumns: true,
            toolbarAlign: "right",
            searchAlign: "right",
            showRefresh: true,
            uniqueId: "ID",
            pageNumber:1,                       //初始化加载第一页，默认第一页
            pageSize: 10,                       //每页的记录行数（*）
            minimumCountColumns: 2,             //最少允许的列数
            clickToSelect: true,                //是否启用点击选中行
            columns: [{
                checkbox: true
            },
                {
                field: 'id',
                title: '文章id'
                },
                {
                field: 'title',
                title: '文章标题'
                },
                {
                field: 'auther',
                title: '作者'
                },
                {
                field: 'edit',
                title: '编辑'
                }

            ]
        });
        // 删除选中行
        $("#btn_delete").click(function() {
            var line_arr = $('#tableId').bootstrapTable('getSelections');
            if (line_arr.length <= 0) {
                alert("请选择一行");
                return;
            }
            else {
                var index = [];
                for(var i=0; i<line_arr.length;i++){
                    article_id = line_arr[i].id;
                    index[i] = article_id;
                    $.ajax({
                        type: "DELETE",
                        url: "/article/delete/" + article_id,
                        fail:function(msg){
                            alert("删除失败")
                        }
                     })
                }
                $("#tableId").bootstrapTable('remove',{
                    field: 'id',
                    values: index
                });
            }
        });
</script>
{% endblock %}

app/templates/article/details.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{%  include ['includes/_detail.html'] %}
{% block scripts %}
{% endblock %}
{% block page_body %}
    <div class="container">
        {# Meta 信息 #}
        <span>作者:{{ article.user.name }}</span> <span>发表日期:{{ article.created | strftime }}</span>
        <a href="edit/{{article.id}}">编辑</a>
        <a id="delete" style="cursor:pointer"  article_id="{{ article.id }}">删除</a>
        <span>点击量({{ article.hit_numers}})</span>
        <span>评论({{ article.comments | length}})</span>
        {# 正文 #}
        <div>
            {{ article.body_html | safe }}
        </div>

        <h4>评论</h4>
        {# 发表评论 #}
        <div>
            {{ wtf.quick_form(form) }}
        </div>

        {# 评论列表 #}
        {% for comment in article.comments|sort(attribute='created') %}
            <div class="media">
                <div class="media-body">
                    <small class="text-muted">{{loop.index}}楼{{ comment.user.name }}@{{ comment.created | strftime }}</small>
                    <div>{{ comment.body }}    <a href="javascript:;" class="reply" comment_id="{{ comment.id }}">回复</a>
                    </div>
                    {% for reply in comment.comments %}
                    <small class="text-muted">{{ reply.user.name }}回复{{comment.user.name}}  {{ reply.created | strftime}}</small>
                    <div>{{ reply.body }}    <a href="javascript:;" class="reply" comment_id="{{ comment.id }}">回复</a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/article/edit.html
{% extends 'base.html' %}
{% include ['includes/_edit.html'] %}
{% block page_body %}
    <div class="container">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{form.title(class="form-group", placeholder="请输入标题") }}
            </div>
            <div>
                <div id="fancy-editormd" class="editormd">
                    {{ form.body(style="display:none;") }}
                </div>
            </div>
            <input class="btn-primary" type="submit" value="发布">
        </form>
    </div>
{% endblock %}