app/main/views.py
import os
from datetime import datetime

from flask import Response
from flask import render_template, request, redirect, url_for
from flask import Blueprint, jsonify
from ..models import Article, Comment, Reply, User, Permission
from .forms import ArticleForm, CommentForm
from flask_login import login_required, current_user
from .. import db
from ..utils.decorators import permission_required
from flask import current_app

main = Blueprint('main', __name__)


@main.route("/")
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config.get("ARTICLE_PER_PAGE", 10)
    pagination = Article.query.filter_by(auther_id=current_user.id).\
        order_by(Article.created.desc()).paginate(page, per_page=per_page)
    articles = pagination.items
    return render_template("index.html", pagination=pagination, articles=articles)


@main.route("/upload", methods=["POST"])
def upload():
    file = request.files.get('editormd-image-file')
    if not file:
        res = {
            'success': 0,
            'message': '上传失败'
        }
    else:
        ex = os.path.splitext(file.filename)[1]
        filename = os.path.join(current_app.root_path, 'static', 'img', datetime.now().strftime('%Y%m%d%H%M%S') + ex)
        print(filename)
        file.save(filename)
        res = {
            'success': 1,
            'message': '上传成功',
            'url': url_for('.image', name=filename)
        }
    return jsonify(res)


@main.route('/image/<name>')
def image(name):
    with open(name, 'rb') as f:
        resp = Response(f.read(), mimetype="image/jpeg")
    return resp


@main.route('/article/list', methods=['GET'])
@login_required
def article_list():
    return render_template("article/article_list.html")


@main.route('/article/data', methods=['GET'])
@login_required
def article_data():
    res = []
    articles = Article.query.options(db.joinedload("user")).filter_by(auther_id=current_user.id).all()
    for article in articles:
        res.append(
            {
                "id": article.id,
                "title": "<a href='%s' style='cursor:pointer'>%s</a>"
                         % (article.id, article.title),
                "auther": article.user.name,
                'edit': "<a href='edit/%s' style='cursor:pointer' >编辑<a>" % article.id
            }
        )

    return jsonify(res)


@main.route('/article/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.COMMENT)
def comments(id):
    article = Article.query.get_or_404(id)
    form = CommentForm(request.form)

    # 保存评论
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, article_id=id, auther_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for(".comments", id=id))
    article.hit_numers += 1
    return render_template("article/details.html",
                           title=article.title,
                           form=form,
                           article=article)


@main.route('/article/edit', methods=['GET', 'POST'])
@main.route('/article/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id=0):
    """
    :param id: 文章id
    :return: post提交，当id为0时，编辑发布新文章，否则编辑旧博客，发布后更新数据库，
    跳转到.comments将博客和评论一并呈现
             get请求时，将文章输入到编辑框中
    """
    form = ArticleForm(request.form)
    # post提交
    if form.validate_on_submit():
        if id == 0:
            article = Article(user=current_user)
        else:
            article = Article.query.get_or_404(id)
        article.body = form.body.data
        article.title = form.title.data

        db.session.add(article)
        db.session.commit()
        # url_for调用处理函数函数名
        return redirect(url_for('.comments', id=article.id))
    # get 编辑时
    title = u'添加文章'
    if id > 0:
        article = Article.query.get_or_404(id)
        form.body.data = article.body
        form.title.data = article.title
        title = u'编辑 %s' % article.title

    return render_template('article/edit.html',
                           title=title,
                           form=form)


@main.route('/article/delete/<int:id>', methods=['DELETE'])
@permission_required(Permission.WRITE)
def delete_article(id):
    article = Article.query.get(id)
    db.session.delete(article)
    db.session.commit()
    res = {
        'success': 0,
        'message': '删除成功',
    }
    return jsonify(res)


@main.route('/reply/<int:article_id>/<int:comment_id>', methods=['POST'])
@login_required
@permission_required(Permission.COMMENT)
def reply(article_id, comment_id):
    reply = Reply(comment_id=comment_id, auther_id=current_user.id)
    reply.body = request.form.get("values")
    db.session.add(reply)
    db.session.commit()
    ret = {
        "data": reply.body
    }
    return jsonify(ret)


@main.route('/about')
def about():
    return render_template('about.html', title=u'关于')

app/templates/includes/_article_list.html
<link href="{{ url_for('static',filename='css/bootstrap.css') }}" rel="stylesheet">
<link href="{{ url_for('static',filename='css/bootstrap-table.css') }}" rel="stylesheet">
<script src="{{ url_for('static',filename='js/jquery-3.5.1.js') }}"> </script>
<script src="{{ url_for('static',filename='js/bootstrap.js') }}" ></script>
<script src="{{ url_for('static',filename='js/bootstrap-table.js') }}"> </script>
<script src="{{ url_for('static',filename='js/bootstrap-table-zh-CN.js') }}"></script>

app/templates/includes/_detail.html
<script src="{{ url_for('static',filename='js/jquery-3.5.1.js') }}"> </script>
<script src="{{ url_for('static',filename='js/details.js') }}"></script>

app/templates/includes/_edit.html
<meta charset="UTF-8">
<link href="{{ url_for('static',filename='editormd/css/editormd.css') }}" rel="stylesheet">
<script src="{{ url_for('static',filename='js/jquery-3.5.1.js') }}"> </script>
<script src="{{ url_for('static',filename='js/editormd.min.js') }}"></script>
<script type="text/javascript">
$(function () {
    var testEditor = editormd("fancy-editormd", {
        // width: "100%", 请不要添加
        height: 640,
        syncScrolling: "single",
        path: "{{url_for('static',filename='editormd/lib/') }}",
        saveHTMLToTextarea : true,

        imageUpload: true, //开启图片上传
        imageUploadURL: "{{url_for('main.upload')}}"
    });
});
</script>

app/templates/includes/_head.html
<meta charset="UTF-8">
<link href="{{ url_for('static',filename='site.css') }}" rel="stylesheet">
<title>{% block title %}{% endblock %}</title>

app/templates/includes/_navbar.html
<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button aria-controls="navbar"
                    aria-expanded="false"
                    class="navbar-toggle collapsed"
                    data-target="#7bc75dbef69e41ff2452de70079c8ece1320ea7c"
                    data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">博客</span>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li {% if url_for('main.index') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.index') }}" title="主页">主页</a>
                </li>
                <li {% if url_for('main.edit') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.edit') }}" title="新文章">新文章</a>
                </li>
                <li {% if url_for('main.article_list') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.article_list') }}" title="博客列表">博客管理</a>
                </li>
                <li {% if url_for('auth.change_password') is current_link %} class="active"{% endif %}>
                    <a href="{{ url_for('auth.change_password') }}" class="dropdown-toggle" data-toggle="dropdown" title="密码管理">密码管理</a>
                    <ul class="dropdown-menu" style="min-width:100%;">
                        <li> <a href={{ url_for('auth.change_password') }}>密码修改</a> </li>
                        <li> <a href={{ url_for('auth.passwd_reset') }}>密码重置</a> </li>
                    </ul>
                </li>
                <li {% if url_for('main.about') is current_link %} class="active"{% endif %}>
                    <a href="{{ url_for('main.about') }}" title="关于">关于我</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="#">{{ current_user.name }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    <li><a href="{{ url_for('auth.register') }}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>